#!/usr/bin/env bash

alias 'ns'='echo "running command: HOST=localhost npm start" HOST=localhost npm start'


# Install packages(s)
function ni {
    if [ -z "$1" ]
    then
        print "Installing packages from package.json"
        npm install
    else
        npm install "$1"
    fi
}

function list_node_versions {
    n
}
function install_node_version {
    if [ -z "$1" ]
    then
        print "Have to specify a node version"
    else
        sudo su
        N_PREFIX="/usr/softwares/node_versions"
        n install "$1"
        exit
        node -v
    fi
}

function set_node_version {
    if [ -z "$1" ]
    then
        print "Have to specify installed node version."
    else
        sudo rm /usr/softwares/node_versions/bin/*
        sudo ln -s /usr/softwares/node_versions/n/versions/node/"$1"/bin/* /usr/softwares/node_versions/bin
        print "Set node version to : $(node -v) "
    fi
}